stas

diff --git a/npl-init/npl-halt b/npl-init/npl-halt
--- a/npl-init/npl-halt
+++ b/npl-init/npl-halt
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ "$(id -u)" -ne 0 ]; then
-    echo "Error: root privileges are required to run this command." >&2
+    echo "root privileges are required to run this command." >&2
     exit 1
 fi
 
