Add root check

diff --git a/npl-init/npl-halt b/npl-init/npl-halt
--- a/npl-init/npl-halt
+++ b/npl-init/npl-halt
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if [ "$(id -u)" -ne 0 ]; then
+    echo "Error: root privileges are required to run this command." >&2
+    exit 1
+fi
+
 ACTION="${0##*/}"
 
 echo "$ACTION" > /halt
